Updated fix permissions to latest

diff --git a/rule1/fix-permissions b/rule1/fix-permissions
--- a/rule1/fix-permissions
+++ b/rule1/fix-permissions
@@ -1,7 +1,26 @@
 #!/bin/sh
-# Fix permissions on the given directory to allow group read/write of
+# https://github.com/omron93/s2i-base-container/blob/26c6610dca178a8681e086043fa1e4e37828ae7b/bin/fix-permissions
+# Allow this script to fail without failing a build
+set +e
+
+# Fix permissions on the given directory or file to allow group read/write of
 # regular files and execute of directories.
-# https://raw.githubusercontent.com/openshift/jenkins/master/1/contrib/jenkins/fix-permissions
-find $1 -exec chgrp 0 {} \;
-find $1 -exec chmod g+rw {} \;
-find $1 -type d -exec chmod g+x {} +
+
+[ $(id -u) -ne 0 ] && CHECK_OWNER=" -uid $(id -u)"
+
+# If argument does not exist, script will still exit with 0,
+# but at least we'll see something went wrong in the log
+if ! [ -e "$1" ] ; then
+  echo "ERROR: File or directory $1 does not exist." >&2
+  # We still want to end successfully
+  exit 0
+fi
+
+find -L "$1" ${CHECK_OWNER} \! -gid 0 -exec chgrp 0 {} +
+find -L "$1" ${CHECK_OWNER} \! -perm -g+rw -exec chmod g+rw {} +
+find -L "$1" ${CHECK_OWNER} -perm /u+x -a \! -perm /g+x -exec chmod g+x {} +
+find -L "$1" ${CHECK_OWNER} -type d \! -perm /g+x -exec chmod g+x {} +
+
+# Always end successfully
+echo "INFO: Fix-permissions DONE." >&2
+exit 0
